Repository piperjarrett/FitLit, pull requests merged in 2022-09, with the labels that each got.

#39 Refarctor/hydrations methods
  src/User.js
  src/data/hydrationTestData.js
  test/User-test.js
Labels: iteration-3

#40 add calender to the HTML and DOM manipulation in script.js
  dist/index.html
  src/User.js
  src/apiCalls.js
  src/css/styles.css
  src/scripts.js
  test/Hydration-test.js
  test/User-test.js
Labels: iteration-4

#41 Functionality/hydration dom
  dist/index.html
  package.json
  src/User.js
  src/css/styles.css
  src/scripts.js
Labels: iteration-3

#42 Feature/charts
  dist/index.html
  src/Sleep.js
  src/User.js
  src/UserRepository.js
  src/apiCalls.js
  src/css/styles.css
  src/data/sleepTestData.js
  src/images/logo_transparent.png
  src/scripts.js
  test/User-test.js
Labels: styling

#76 Feature/user activity
  src/User.js
  src/UserActivity.js
  src/data/userActivityTestData.js
  test/UserActivity-test.js
Labels: iteration-5

#84 Feature/dom manipulation miles steps active minutes
  dist/index.html
  src/UserActivity.js
  src/css/styles.css
  src/scripts.js
Labels: iteration-5

#86 Add: form for adding new data
  dist/index.html
  src/css/styles.css
  src/images/moon.png
  src/images/sun.svg
  src/scripts.js
Labels: iteration-5

#87 Feature/activity methods
  dist/index.html
  src/User.js
  src/UserActivity.js
  src/UserRepository.js
  src/css/styles.css
  src/data/userActivityTestData.js
  src/scripts.js
  test/UserActivity-test.js
  test/UserRepository-test.js
Labels: iteration-5

#90 Feature/display weekly activity
  dist/index.html
  src/UserActivity.js
  src/UserRepository.js
  src/css/styles.css
  src/scripts.js
  test/UserActivity-test.js
  test/UserRepository-test.js
Labels: iteration-5

#92 Css/styling
  dist/index.html
  src/css/styles.css
  src/images/arrow_back.png
  src/scripts.js
Labels: styling
