Repository piperjarrett/FitLit, pull requests merged in 2022-08, with the labels that each got.

#24 Add daily step goal test and remove deep equal
  src/User.js
  test/User-test.js
Labels: iteration-1

#26 add html skeleton
  assets/dumbbells-exercise.svg
  assets/sleep-mode.svg
  assets/sun-1.svg
  assets/water-bottle.svg
  dist/index.html
Labels: iteration-1

#27 begin querySelectors and DOM manipulation
  src/UserRepository.js
  src/scripts.js
Labels: iteration-1

#28 Feature/html update
  dist/avatar-male.png
  dist/gym.png
  dist/index.html
  dist/lighting.png
  dist/logo_transparent.png
  dist/water-bottle.png
  src/css/styles.css
Labels: iteration-1, styling

#29 Styling/create boxes
  assets/dumbbells-exercise.svg
  assets/sleep-mode.svg
  assets/sun-1.svg
  assets/water-bottle.svg
  dist/index.html
  src/User.js
  src/UserRepository.js
  src/css/styles.css
  src/images/avatar-male.png
  src/images/gym.png
  src/images/lighting.png
  src/images/logo_transparent.png
  src/images/sandals.png
  src/images/water-bottle.png
  src/scripts.js
Labels: iteration-1, styling

#33 add User fetch calls
  src/apiCalls.js
  src/scripts.js
Labels: iteration-2

#34 Write TDD and Sleep class, add test sleep data.
  src/Sleep.js
  src/data/sleepTestData.js
  test/Sleep-test.js
Labels: iteration-4

#35 Add: test for getWeeklyFluids
  src/User.js
Labels: iteration-3

#36 Test/hydration test
  test/Hydration-test.js
Labels: iteration-3

#37 Add average and date methods for sleep
  src/User.js
  src/UserRepository.js
  src/data/sleepTestData.js
  test/User-test.js
  test/UserRepository-test.js
Labels: iteration-4
